### ISSUE TITLE
Greenkeeper bot is dead, migrate to another bot

### ISSUE THREAD

**Issue by HonkingGoose** [standard/standard#1550]
**What version of this package are you using?**

Not relevant.

**What operating system, Node.js, and npm version?**

Not relevant.

**What happened?**

Your Greenkeeper dependency checker bot is dead.

Quote from the [Greenkeeper.io website](https://greenkeeper.io/):
> We’ll stop Greenkeeper’s operation as an independent service on June 3rd, 2020.
> For your dependency update needs, we have a brilliant alternative for you: **Snyk**.

This means there are no automated dependency checks anymore.

**What did you expect to happen?**

A bot that checks for updates to dependencies is running on this repository.

**Are you willing to submit a pull request to fix this bug?**

Yes, I can get you a Dependabot configuration tuned to your liking if you want.
I can also get you pointed in the right direction for Renovate.

**Migrate to Dependabot**

This is probably the easiest migration I can offer you, because I can do the configuration work for **Dependabot** together with you. If you want I can open a pull request that gets you a basic Dependabot configuration, which I will then tune to your liking according to your feedback.

The main benefit of Dependabot is that it's easy to use and integrated into GitHub. You won't need to use another app/website to manage the bot.

The downside is that you can't really configure Dependabot to only offer certain patch level updates (major only, major and minor, major + minor + patch). Dependabot also doesn't know how to group updates together that should be upgraded as a group.

[Dependabot Documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically)

**Migrate to Depfu**

Or you can take a look at **Depfu**, which supports setting the level of updates you want, and will group updates that belong together into one pull request by default.

[Depfu app on GitHub Marketplace](https://github.com/marketplace/depfu)

**Migrate to Renovate**

Or maybe you like **Renovate** better, it also supports setting the level of updates you want, and supports grouping updates that belong together into one pull request (most known monorepos are grouped by default).

Renovate is quite easy to get started with, they have a "getting started" pull request, that helps you to configure the bot to your liking.

[Renovate app on GitHub Marketplace](https://github.com/marketplace/renovate)

**Migrate to Snyk**

Or you can do what Greenkeeper suggests and use Snyk.
[Snyk app on GitHub marketplace](https://github.com/marketplace/snyk)

**Checklist for migration**

- [x] Decide which bot you want to use.
- [x] If you want to use Dependabot, ping me, and I'll make a basic config, and ask you what you want/don't want.
- [ ] Ensure new bot works.
- [ ] Remove Greenkeeper app from this repository.
- [x] Close old Greenkeeper pull requests.

**Comment by feross** [comment]
Hi there! Thanks for the offer to help! Can you send a PR to use Dependabot?

**Comment by HonkingGoose** [comment]
Will do. Can you please assign me to this issue. I'll open a pull request for you when I have time. :wink: 

https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users
