### ISSUE TITLE
Release proposal: 15.0.0

### ISSUE THREAD

**Issue by LinusU** [standard/standard#1560]
We'll have to do a major version to get ESLint 7.x support, and I wanted to see if there is anything else we want to merge in as well. My preliminary list:

- [x] ESLint 7 standard/eslint-config-standard#169 standard/eslint-config-standard#170 
- [x] Cleanup standard/eslint-config-standard#160 
- [x] ES2020 globals standard/eslint-config-standard#156 
- [x] Remove no-inner-declarations standard/eslint-config-standard#154

Breaks old runtime compat:
- [ ] Object Shorthand standard/eslint-config-standard#166 
- [ ] no-var standard/eslint-config-standard#152 

High eco system breakage: 
- [ ] catch-or-return standard/eslint-config-standard#148
- [ ] multiline-comment-style standard/eslint-config-standard#94

**Comment by feross** [comment]
standard 15.0.0 is released! This release took me 6 hours of work to put together.

Announcement tweet: https://twitter.com/StandardJS/status/1319109569675554816
Changelog: https://standardjs.com/changelog.html#1500---2020-10-21

Hope you enjoy it!
