### ISSUE TITLE
Tracking issue `test-external`

### ISSUE THREAD

**Issue by Divlo** [standard/standard#1777]
**What version of this package are you using?**

`standard@17.0.0-2`

**What happened?**

`test-external` is currently failing, before releasing `standard@17.0.0` stable we should ensure that the ecosystem is ready.
Here are the failing repos:

- [ ] https://github.com/feross/simple-get
- [ ] https://github.com/webtorrent/webtorrent
- [ ] https://github.com/marcbachmann/node-html-pdf (https://github.com/marcbachmann/node-html-pdf/pull/657)
- [x] https://github.com/jprichardson/electron-mocha (https://github.com/jprichardson/electron-mocha/pull/193)
- [ ] https://github.com/feross/chrome-net
- [ ] https://github.com/libp2p/js-libp2p-tcp
- [ ] https://github.com/feross/safe-buffer
- [ ] https://github.com/yargs/yargs-parser
- [x] https://github.com/Level/leveldown (https://github.com/Level/leveldown/pull/800) (they want to merge when `standard@17` stable, so we can temporarily disable them for releasing)
- [x] https://github.com/fastify/fastify (https://github.com/fastify/fastify/pull/3682)
- [ ] https://github.com/maxogden/extract-zip (https://github.com/maxogden/extract-zip/pull/128)

**Comment by voxpelli** [comment]
Are we sure all of these are correct failures? Or are some caused by unintended side-effects?

When I get time to finish https://github.com/standard/standard/pull/1747 this will be easier to see 🤔

**Comment by LinusU** [comment]
https://github.com/feross/simple-get/pull/78 would fix `simple-get`, but it's a breaking change 😅

**Comment by Divlo** [comment]
I closed some of my PRs because there are no activities and also because I don't want/have time to do the job for this, feel free to open other PRs to fix the linting issues with standard v17.

**Comment by voxpelli** [comment]
Current status of errors:

### Caused by switch to `eslint-plugin-n`

Will need an update once they upgrade, but isn't any actual regression.

* [ ] `feross/chrome-net` fails due to disabling of `node/` rule that needs to be updated to instead disable the `n/` rule
* [ ] `feross/safe-buffer` fails due to disabling of `node/` rule that needs to be updated to instead disable the `n/` rule
* [ ] `feross/simple-get` fails due to disabling of `node/` rule that needs to be updated to instead disable the `n/` rule
* [ ] `feross/studynotes.org` fails due to disabling of `node/` rule that needs to be updated to instead disable the `n/` rule
* [ ] `maxogden/extract-zip` fails due to disabling of `node/` rule that needs to be updated to instead disable the `n/` rule

### Caused by `eslint 7.19.0`

Not blocking `eslint-config-standard` from going stable at all.

* [ ] `webtorrent/webtorrent` is caused by `eslint 7.19.0`, not `standard 17`, as described in: https://github.com/standard/standard/pull/1702#issuecomment-932961087
* [ ] `Level/leveldown` is caused by `eslint 7.19.0`, not `standard 17`, as described in: https://github.com/standard/standard/pull/1702#issuecomment-932961087

### Causes an error

We should figure out why

* [ ] `libp2p/js-libp2p-tcp` causes an unexpected linter output: `Error: All files matched by '.' are ignored.`

### Causes extra failures

We should check that this isn't an unintended regression

* [ ] `marcbachmann/node-html-pdf` fails on lots of things: `no-useless-escape`, `object-curly-spacing`, `indent`
* [ ] `yargs/yargs-parser` fails in `test/yargs-parser.mjs` because of: `eol-last`, `no-undef`

**Comment by Kdawg5508** [comment]
Appreciate your honesty I'll take my business elsewhere. I wasted five
months with you all
